name: huungry
description: "3M CODE APP"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.0.2
  flutter_svg: ^2.2.1
  equatable: ^2.0.5
  gap: ^3.0.1
  flutter_screenutil: ^5.9.3
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  skeletonizer: ^2.1.0
  image_picker: ^1.2.0
  animate_icons: ^2.0.0
  provider: ^6.0.5
  flutter_secure_storage: ^9.2.4
  logger: ^2.6.2
  flutter_animate: ^4.5.2
  lottie: ^3.3.2
  easy_localization: ^3.0.8
  google_maps_flutter: ^2.14.0
  location: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/splash/
    - assets/test/
    - assets/detail/
    - assets/icon/
    - assets/banner/
    - assets/onboarding/
    - assets/translations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
